2023-12-19 16:58:43,633:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-19 16:58:43,634:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-19 16:58:43,635:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-19 16:58:43,635:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-19 17:00:11,302:INFO:PyCaret ClassificationExperiment
2023-12-19 17:00:11,303:INFO:Logging name: clf-default-name
2023-12-19 17:00:11,305:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-12-19 17:00:11,305:INFO:version 3.2.0
2023-12-19 17:00:11,306:INFO:Initializing setup()
2023-12-19 17:00:11,308:INFO:self.USI: 1e29
2023-12-19 17:00:11,309:INFO:self._variable_keys: {'gpu_n_jobs_param', 'y', 'X_train', '_ml_usecase', 'X_test', 'gpu_param', 'html_param', 'log_plots_param', 'fold_shuffle_param', 'seed', 'fold_groups_param', 'y_train', 'X', 'exp_name_log', 'is_multiclass', 'n_jobs_param', 'pipeline', 'memory', 'target_param', 'logging_param', 'data', 'idx', 'USI', 'fix_imbalance', 'fold_generator', 'y_test', 'exp_id', '_available_plots'}
2023-12-19 17:00:11,310:INFO:Checking environment
2023-12-19 17:00:11,310:INFO:python_version: 3.11.6
2023-12-19 17:00:11,310:INFO:python_build: ('main', 'Oct  3 2023 00:00:00')
2023-12-19 17:00:11,311:INFO:machine: x86_64
2023-12-19 17:00:11,311:INFO:platform: Linux-6.6.6-100.fc38.x86_64-x86_64-with-glibc2.37
2023-12-19 17:00:11,313:INFO:Memory: svmem(total=16658345984, available=7754362880, percent=53.5, used=7625703424, free=653029376, active=11569356800, inactive=2743545856, buffers=61440, cached=8379551744, shared=928505856, slab=1142259712)
2023-12-19 17:00:11,321:INFO:Physical Core: 2
2023-12-19 17:00:11,322:INFO:Logical Core: 4
2023-12-19 17:00:11,323:INFO:Checking libraries
2023-12-19 17:00:11,324:INFO:System:
2023-12-19 17:00:11,325:INFO:    python: 3.11.6 (main, Oct  3 2023, 00:00:00) [GCC 13.2.1 20230728 (Red Hat 13.2.1-1)]
2023-12-19 17:00:11,325:INFO:executable: /home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/bin/python
2023-12-19 17:00:11,325:INFO:   machine: Linux-6.6.6-100.fc38.x86_64-x86_64-with-glibc2.37
2023-12-19 17:00:11,326:INFO:PyCaret required dependencies:
2023-12-19 17:00:11,650:INFO:                 pip: 23.3.2
2023-12-19 17:00:11,651:INFO:          setuptools: 65.5.1
2023-12-19 17:00:11,652:INFO:             pycaret: 3.2.0
2023-12-19 17:00:11,652:INFO:             IPython: 8.18.1
2023-12-19 17:00:11,652:INFO:          ipywidgets: 8.1.1
2023-12-19 17:00:11,652:INFO:                tqdm: 4.66.1
2023-12-19 17:00:11,653:INFO:               numpy: 1.25.2
2023-12-19 17:00:11,653:INFO:              pandas: 1.5.3
2023-12-19 17:00:11,653:INFO:              jinja2: 3.1.2
2023-12-19 17:00:11,654:INFO:               scipy: 1.10.1
2023-12-19 17:00:11,654:INFO:              joblib: 1.3.2
2023-12-19 17:00:11,654:INFO:             sklearn: 1.2.2
2023-12-19 17:00:11,655:INFO:                pyod: 1.1.2
2023-12-19 17:00:11,655:INFO:            imblearn: 0.11.0
2023-12-19 17:00:11,656:INFO:   category_encoders: 2.6.3
2023-12-19 17:00:11,656:INFO:            lightgbm: 4.1.0
2023-12-19 17:00:11,656:INFO:               numba: 0.58.1
2023-12-19 17:00:11,657:INFO:            requests: 2.31.0
2023-12-19 17:00:11,657:INFO:          matplotlib: 3.6.0
2023-12-19 17:00:11,657:INFO:          scikitplot: 0.3.7
2023-12-19 17:00:11,658:INFO:         yellowbrick: 1.5
2023-12-19 17:00:11,658:INFO:              plotly: 5.18.0
2023-12-19 17:00:11,658:INFO:    plotly-resampler: Not installed
2023-12-19 17:00:11,659:INFO:             kaleido: 0.2.1
2023-12-19 17:00:11,659:INFO:           schemdraw: 0.15
2023-12-19 17:00:11,660:INFO:         statsmodels: 0.14.1
2023-12-19 17:00:11,660:INFO:              sktime: 0.21.1
2023-12-19 17:00:11,660:INFO:               tbats: 1.1.3
2023-12-19 17:00:11,660:INFO:            pmdarima: 2.0.4
2023-12-19 17:00:11,661:INFO:              psutil: 5.9.7
2023-12-19 17:00:11,661:INFO:          markupsafe: 2.1.3
2023-12-19 17:00:11,661:INFO:             pickle5: Not installed
2023-12-19 17:00:11,662:INFO:         cloudpickle: 3.0.0
2023-12-19 17:00:11,662:INFO:         deprecation: 2.1.0
2023-12-19 17:00:11,663:INFO:              xxhash: 3.4.1
2023-12-19 17:00:11,663:INFO:           wurlitzer: 3.0.3
2023-12-19 17:00:11,663:INFO:PyCaret optional dependencies:
2023-12-19 17:00:11,965:INFO:                shap: Not installed
2023-12-19 17:00:11,966:INFO:           interpret: Not installed
2023-12-19 17:00:11,966:INFO:                umap: Not installed
2023-12-19 17:00:11,966:INFO:     ydata_profiling: Not installed
2023-12-19 17:00:11,967:INFO:  explainerdashboard: Not installed
2023-12-19 17:00:11,969:INFO:             autoviz: Not installed
2023-12-19 17:00:11,971:INFO:           fairlearn: Not installed
2023-12-19 17:00:11,971:INFO:          deepchecks: Not installed
2023-12-19 17:00:11,971:INFO:             xgboost: Not installed
2023-12-19 17:00:11,972:INFO:            catboost: Not installed
2023-12-19 17:00:11,972:INFO:              kmodes: Not installed
2023-12-19 17:00:11,972:INFO:             mlxtend: Not installed
2023-12-19 17:00:11,973:INFO:       statsforecast: Not installed
2023-12-19 17:00:11,974:INFO:        tune_sklearn: Not installed
2023-12-19 17:00:11,975:INFO:                 ray: Not installed
2023-12-19 17:00:11,975:INFO:            hyperopt: Not installed
2023-12-19 17:00:11,976:INFO:              optuna: Not installed
2023-12-19 17:00:11,976:INFO:               skopt: Not installed
2023-12-19 17:00:11,977:INFO:              mlflow: Not installed
2023-12-19 17:00:11,978:INFO:              gradio: Not installed
2023-12-19 17:00:11,980:INFO:             fastapi: Not installed
2023-12-19 17:00:11,984:INFO:             uvicorn: Not installed
2023-12-19 17:00:11,989:INFO:              m2cgen: Not installed
2023-12-19 17:00:11,989:INFO:           evidently: Not installed
2023-12-19 17:00:11,990:INFO:               fugue: Not installed
2023-12-19 17:00:11,994:INFO:           streamlit: Not installed
2023-12-19 17:00:11,995:INFO:             prophet: Not installed
2023-12-19 17:00:11,995:INFO:None
2023-12-19 17:00:11,996:INFO:Set up data.
2023-12-19 17:00:13,835:INFO:Set up folding strategy.
2023-12-19 17:00:13,835:INFO:Set up train/test split.
2023-12-19 17:00:13,925:INFO:Set up index.
2023-12-19 17:00:13,926:INFO:Assigning column types.
2023-12-19 17:00:13,993:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-12-19 17:00:14,333:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-12-19 17:00:14,340:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-19 17:00:14,581:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-19 17:00:14,584:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-19 17:00:15,013:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-12-19 17:00:15,021:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-19 17:00:15,248:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-19 17:00:15,251:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-19 17:00:15,254:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-12-19 17:00:15,605:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-19 17:00:15,862:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-19 17:00:15,863:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-19 17:00:16,240:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-19 17:00:16,465:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-19 17:00:16,466:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-19 17:00:16,469:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-12-19 17:00:17,305:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-19 17:00:17,307:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-19 17:00:17,930:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-19 17:00:17,932:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-19 17:00:17,941:INFO:Preparing preprocessing pipeline...
2023-12-19 17:00:17,949:INFO:Set up simple imputation.
2023-12-19 17:00:18,249:INFO:Finished creating preprocessing pipeline.
2023-12-19 17:00:18,313:INFO:Pipeline: Pipeline(memory=FastMemory(location=/tmp/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['0', '1', '2', '3', '4', '5', '6',
                                             '7', '8', '9', '10', '11', '12',
                                             '13', '14', '15', '16', '17', '18',
                                             '19', '20', '21', '22', '23', '24',
                                             '25', '26', '27', '28', '29', ...],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecated'))),
                ('categorical_imputer',
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated')))],
         verbose=False)
2023-12-19 17:00:18,314:INFO:Creating final display dataframe.
2023-12-19 17:00:19,894:INFO:Setup _display_container:                     Description             Value
0                    Session id              7350
1                        Target            target
2                   Target type            Binary
3           Original data shape       (1093, 513)
4        Transformed data shape       (1093, 513)
5   Transformed train set shape        (765, 513)
6    Transformed test set shape        (328, 513)
7              Numeric features               512
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              1e29
2023-12-19 17:00:20,736:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-19 17:00:20,738:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-19 17:00:21,371:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-19 17:00:21,372:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-19 17:00:21,375:INFO:setup() successfully completed in 10.08s...............
2023-12-19 17:00:21,376:INFO:Initializing compare_models()
2023-12-19 17:00:21,376:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f156a265710>, include=None, exclude=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x7f156a265710>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>})
2023-12-19 17:00:21,377:INFO:Checking exceptions
2023-12-19 17:00:21,404:INFO:Preparing display monitor
2023-12-19 17:00:21,577:INFO:Initializing Logistic Regression
2023-12-19 17:00:21,577:INFO:Total runtime is 8.626778920491536e-06 minutes
2023-12-19 17:00:21,601:INFO:SubProcess create_model() called ==================================
2023-12-19 17:00:21,602:INFO:Initializing create_model()
2023-12-19 17:00:21,603:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f156a265710>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f156a1b1890>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-19 17:00:21,603:INFO:Checking exceptions
2023-12-19 17:00:21,605:INFO:Importing libraries
2023-12-19 17:00:21,606:INFO:Copying training dataset
2023-12-19 17:00:21,684:INFO:Defining folds
2023-12-19 17:00:21,685:INFO:Declaring metric variables
2023-12-19 17:00:21,718:INFO:Importing untrained model
2023-12-19 17:00:21,753:INFO:Logistic Regression Imported successfully
2023-12-19 17:00:21,943:INFO:Starting cross validation
2023-12-19 17:00:21,974:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-19 17:00:47,364:INFO:Calculating mean and std
2023-12-19 17:00:47,382:INFO:Creating metrics dataframe
2023-12-19 17:00:47,441:INFO:Uploading results into container
2023-12-19 17:00:47,447:INFO:Uploading model into container now
2023-12-19 17:00:47,450:INFO:_master_model_container: 1
2023-12-19 17:00:47,451:INFO:_display_container: 2
2023-12-19 17:00:47,454:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=7350, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-12-19 17:00:47,454:INFO:create_model() successfully completed......................................
2023-12-19 17:00:47,874:INFO:SubProcess create_model() end ==================================
2023-12-19 17:00:47,874:INFO:Creating metrics dataframe
2023-12-19 17:00:47,968:INFO:Initializing K Neighbors Classifier
2023-12-19 17:00:47,969:INFO:Total runtime is 0.4398772676785787 minutes
2023-12-19 17:00:47,993:INFO:SubProcess create_model() called ==================================
2023-12-19 17:00:47,996:INFO:Initializing create_model()
2023-12-19 17:00:47,998:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f156a265710>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f156a1b1890>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-19 17:00:47,998:INFO:Checking exceptions
2023-12-19 17:00:47,999:INFO:Importing libraries
2023-12-19 17:00:47,999:INFO:Copying training dataset
2023-12-19 17:00:48,060:INFO:Defining folds
2023-12-19 17:00:48,060:INFO:Declaring metric variables
2023-12-19 17:00:48,089:INFO:Importing untrained model
2023-12-19 17:00:48,120:INFO:K Neighbors Classifier Imported successfully
2023-12-19 17:00:48,178:INFO:Starting cross validation
2023-12-19 17:00:48,196:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-19 17:00:51,093:INFO:Calculating mean and std
2023-12-19 17:00:51,111:INFO:Creating metrics dataframe
2023-12-19 17:00:51,248:INFO:Uploading results into container
2023-12-19 17:00:51,255:INFO:Uploading model into container now
2023-12-19 17:00:51,262:INFO:_master_model_container: 2
2023-12-19 17:00:51,267:INFO:_display_container: 2
2023-12-19 17:00:51,274:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-12-19 17:00:51,276:INFO:create_model() successfully completed......................................
2023-12-19 17:00:51,553:INFO:SubProcess create_model() end ==================================
2023-12-19 17:00:51,553:INFO:Creating metrics dataframe
2023-12-19 17:00:51,626:INFO:Initializing Naive Bayes
2023-12-19 17:00:51,627:INFO:Total runtime is 0.5008390545845032 minutes
2023-12-19 17:00:51,663:INFO:SubProcess create_model() called ==================================
2023-12-19 17:00:51,668:INFO:Initializing create_model()
2023-12-19 17:00:51,669:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f156a265710>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f156a1b1890>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-19 17:00:51,669:INFO:Checking exceptions
2023-12-19 17:00:51,673:INFO:Importing libraries
2023-12-19 17:00:51,673:INFO:Copying training dataset
2023-12-19 17:00:51,734:INFO:Defining folds
2023-12-19 17:00:51,734:INFO:Declaring metric variables
2023-12-19 17:00:51,760:INFO:Importing untrained model
2023-12-19 17:00:51,786:INFO:Naive Bayes Imported successfully
2023-12-19 17:00:51,904:INFO:Starting cross validation
2023-12-19 17:00:51,931:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-19 17:00:54,141:INFO:Calculating mean and std
2023-12-19 17:00:54,159:INFO:Creating metrics dataframe
2023-12-19 17:00:54,197:INFO:Uploading results into container
2023-12-19 17:00:54,201:INFO:Uploading model into container now
2023-12-19 17:00:54,203:INFO:_master_model_container: 3
2023-12-19 17:00:54,203:INFO:_display_container: 2
2023-12-19 17:00:54,204:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-12-19 17:00:54,204:INFO:create_model() successfully completed......................................
2023-12-19 17:00:54,495:INFO:SubProcess create_model() end ==================================
2023-12-19 17:00:54,495:INFO:Creating metrics dataframe
2023-12-19 17:00:54,593:INFO:Initializing Decision Tree Classifier
2023-12-19 17:00:54,595:INFO:Total runtime is 0.5503018617630004 minutes
2023-12-19 17:00:54,614:INFO:SubProcess create_model() called ==================================
2023-12-19 17:00:54,615:INFO:Initializing create_model()
2023-12-19 17:00:54,616:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f156a265710>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f156a1b1890>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-19 17:00:54,616:INFO:Checking exceptions
2023-12-19 17:00:54,623:INFO:Importing libraries
2023-12-19 17:00:54,626:INFO:Copying training dataset
2023-12-19 17:00:54,685:INFO:Defining folds
2023-12-19 17:00:54,686:INFO:Declaring metric variables
2023-12-19 17:00:54,725:INFO:Importing untrained model
2023-12-19 17:00:54,765:INFO:Decision Tree Classifier Imported successfully
2023-12-19 17:00:54,842:INFO:Starting cross validation
2023-12-19 17:00:54,873:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-19 17:01:04,164:INFO:Calculating mean and std
2023-12-19 17:01:04,171:INFO:Creating metrics dataframe
2023-12-19 17:01:04,199:INFO:Uploading results into container
2023-12-19 17:01:04,206:INFO:Uploading model into container now
2023-12-19 17:01:04,209:INFO:_master_model_container: 4
2023-12-19 17:01:04,209:INFO:_display_container: 2
2023-12-19 17:01:04,212:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=7350, splitter='best')
2023-12-19 17:01:04,212:INFO:create_model() successfully completed......................................
2023-12-19 17:01:04,484:INFO:SubProcess create_model() end ==================================
2023-12-19 17:01:04,485:INFO:Creating metrics dataframe
2023-12-19 17:01:04,555:INFO:Initializing SVM - Linear Kernel
2023-12-19 17:01:04,556:INFO:Total runtime is 0.7163183530171712 minutes
2023-12-19 17:01:04,574:INFO:SubProcess create_model() called ==================================
2023-12-19 17:01:04,576:INFO:Initializing create_model()
2023-12-19 17:01:04,578:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f156a265710>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f156a1b1890>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-19 17:01:04,578:INFO:Checking exceptions
2023-12-19 17:01:04,578:INFO:Importing libraries
2023-12-19 17:01:04,578:INFO:Copying training dataset
2023-12-19 17:01:04,631:INFO:Defining folds
2023-12-19 17:01:04,631:INFO:Declaring metric variables
2023-12-19 17:01:04,653:INFO:Importing untrained model
2023-12-19 17:01:04,681:INFO:SVM - Linear Kernel Imported successfully
2023-12-19 17:01:04,737:INFO:Starting cross validation
2023-12-19 17:01:04,762:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-19 17:01:05,279:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-19 17:01:05,526:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-19 17:01:05,567:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-19 17:01:05,833:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-19 17:01:05,923:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-19 17:01:06,009:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-19 17:01:06,320:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-19 17:01:06,541:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-19 17:01:06,600:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-19 17:01:06,648:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-19 17:01:06,799:INFO:Calculating mean and std
2023-12-19 17:01:06,806:INFO:Creating metrics dataframe
2023-12-19 17:01:06,827:INFO:Uploading results into container
2023-12-19 17:01:06,830:INFO:Uploading model into container now
2023-12-19 17:01:06,832:INFO:_master_model_container: 5
2023-12-19 17:01:06,834:INFO:_display_container: 2
2023-12-19 17:01:06,837:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=7350, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-12-19 17:01:06,837:INFO:create_model() successfully completed......................................
2023-12-19 17:01:07,144:INFO:SubProcess create_model() end ==================================
2023-12-19 17:01:07,145:INFO:Creating metrics dataframe
2023-12-19 17:01:07,234:INFO:Initializing Ridge Classifier
2023-12-19 17:01:07,235:INFO:Total runtime is 0.7609692056973775 minutes
2023-12-19 17:01:07,259:INFO:SubProcess create_model() called ==================================
2023-12-19 17:01:07,260:INFO:Initializing create_model()
2023-12-19 17:01:07,262:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f156a265710>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f156a1b1890>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-19 17:01:07,262:INFO:Checking exceptions
2023-12-19 17:01:07,262:INFO:Importing libraries
2023-12-19 17:01:07,263:INFO:Copying training dataset
2023-12-19 17:01:07,313:INFO:Defining folds
2023-12-19 17:01:07,314:INFO:Declaring metric variables
2023-12-19 17:01:07,347:INFO:Importing untrained model
2023-12-19 17:01:07,373:INFO:Ridge Classifier Imported successfully
2023-12-19 17:01:07,427:INFO:Starting cross validation
2023-12-19 17:01:07,442:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-19 17:01:07,983:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-19 17:01:08,007:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-19 17:01:08,015:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-19 17:01:08,033:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-19 17:01:08,558:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-19 17:01:08,611:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-19 17:01:08,806:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-19 17:01:08,897:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-19 17:01:08,961:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-19 17:01:09,209:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-19 17:01:09,275:INFO:Calculating mean and std
2023-12-19 17:01:09,286:INFO:Creating metrics dataframe
2023-12-19 17:01:09,315:INFO:Uploading results into container
2023-12-19 17:01:09,318:INFO:Uploading model into container now
2023-12-19 17:01:09,321:INFO:_master_model_container: 6
2023-12-19 17:01:09,321:INFO:_display_container: 2
2023-12-19 17:01:09,322:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=7350, solver='auto',
                tol=0.0001)
2023-12-19 17:01:09,323:INFO:create_model() successfully completed......................................
2023-12-19 17:01:09,608:INFO:SubProcess create_model() end ==================================
2023-12-19 17:01:09,609:INFO:Creating metrics dataframe
2023-12-19 17:01:09,674:INFO:Initializing Random Forest Classifier
2023-12-19 17:01:09,675:INFO:Total runtime is 0.8016345659891764 minutes
2023-12-19 17:01:09,696:INFO:SubProcess create_model() called ==================================
2023-12-19 17:01:09,701:INFO:Initializing create_model()
2023-12-19 17:01:09,702:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f156a265710>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f156a1b1890>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-19 17:01:09,702:INFO:Checking exceptions
2023-12-19 17:01:09,702:INFO:Importing libraries
2023-12-19 17:01:09,702:INFO:Copying training dataset
2023-12-19 17:01:09,753:INFO:Defining folds
2023-12-19 17:01:09,754:INFO:Declaring metric variables
2023-12-19 17:01:09,786:INFO:Importing untrained model
2023-12-19 17:01:09,813:INFO:Random Forest Classifier Imported successfully
2023-12-19 17:01:09,872:INFO:Starting cross validation
2023-12-19 17:01:09,898:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-19 17:01:30,064:INFO:Calculating mean and std
2023-12-19 17:01:30,069:INFO:Creating metrics dataframe
2023-12-19 17:01:30,089:INFO:Uploading results into container
2023-12-19 17:01:30,094:INFO:Uploading model into container now
2023-12-19 17:01:30,096:INFO:_master_model_container: 7
2023-12-19 17:01:30,097:INFO:_display_container: 2
2023-12-19 17:01:30,100:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=7350, verbose=0, warm_start=False)
2023-12-19 17:01:30,101:INFO:create_model() successfully completed......................................
2023-12-19 17:01:30,356:INFO:SubProcess create_model() end ==================================
2023-12-19 17:01:30,357:INFO:Creating metrics dataframe
2023-12-19 17:01:30,423:INFO:Initializing Quadratic Discriminant Analysis
2023-12-19 17:01:30,423:INFO:Total runtime is 1.147447379430135 minutes
2023-12-19 17:01:30,445:INFO:SubProcess create_model() called ==================================
2023-12-19 17:01:30,446:INFO:Initializing create_model()
2023-12-19 17:01:30,447:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f156a265710>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f156a1b1890>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-19 17:01:30,448:INFO:Checking exceptions
2023-12-19 17:01:30,448:INFO:Importing libraries
2023-12-19 17:01:30,448:INFO:Copying training dataset
2023-12-19 17:01:30,492:INFO:Defining folds
2023-12-19 17:01:30,492:INFO:Declaring metric variables
2023-12-19 17:01:30,513:INFO:Importing untrained model
2023-12-19 17:01:30,537:INFO:Quadratic Discriminant Analysis Imported successfully
2023-12-19 17:01:30,581:INFO:Starting cross validation
2023-12-19 17:01:30,596:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-19 17:01:31,211:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-19 17:01:31,588:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-19 17:01:31,792:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-19 17:01:31,908:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-19 17:01:32,408:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-19 17:01:33,099:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-19 17:01:33,744:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-19 17:01:33,871:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-19 17:01:34,318:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-19 17:01:34,764:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-19 17:01:35,375:INFO:Calculating mean and std
2023-12-19 17:01:35,380:INFO:Creating metrics dataframe
2023-12-19 17:01:35,399:INFO:Uploading results into container
2023-12-19 17:01:35,403:INFO:Uploading model into container now
2023-12-19 17:01:35,406:INFO:_master_model_container: 8
2023-12-19 17:01:35,406:INFO:_display_container: 2
2023-12-19 17:01:35,408:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-12-19 17:01:35,408:INFO:create_model() successfully completed......................................
2023-12-19 17:01:35,647:INFO:SubProcess create_model() end ==================================
2023-12-19 17:01:35,647:INFO:Creating metrics dataframe
2023-12-19 17:01:35,729:INFO:Initializing Ada Boost Classifier
2023-12-19 17:01:35,730:INFO:Total runtime is 1.2358837286631266 minutes
2023-12-19 17:01:35,750:INFO:SubProcess create_model() called ==================================
2023-12-19 17:01:35,752:INFO:Initializing create_model()
2023-12-19 17:01:35,753:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f156a265710>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f156a1b1890>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-19 17:01:35,754:INFO:Checking exceptions
2023-12-19 17:01:35,754:INFO:Importing libraries
2023-12-19 17:01:35,754:INFO:Copying training dataset
2023-12-19 17:01:35,802:INFO:Defining folds
2023-12-19 17:01:35,803:INFO:Declaring metric variables
2023-12-19 17:01:35,833:INFO:Importing untrained model
2023-12-19 17:01:35,861:INFO:Ada Boost Classifier Imported successfully
2023-12-19 17:01:35,912:INFO:Starting cross validation
2023-12-19 17:01:35,929:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-19 17:02:25,002:INFO:Calculating mean and std
2023-12-19 17:02:25,009:INFO:Creating metrics dataframe
2023-12-19 17:02:25,030:INFO:Uploading results into container
2023-12-19 17:02:25,033:INFO:Uploading model into container now
2023-12-19 17:02:25,038:INFO:_master_model_container: 9
2023-12-19 17:02:25,038:INFO:_display_container: 2
2023-12-19 17:02:25,040:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=7350)
2023-12-19 17:02:25,040:INFO:create_model() successfully completed......................................
2023-12-19 17:02:25,326:INFO:SubProcess create_model() end ==================================
2023-12-19 17:02:25,326:INFO:Creating metrics dataframe
2023-12-19 17:02:25,396:INFO:Initializing Gradient Boosting Classifier
2023-12-19 17:02:25,396:INFO:Total runtime is 2.063660248120626 minutes
2023-12-19 17:02:25,421:INFO:SubProcess create_model() called ==================================
2023-12-19 17:02:25,422:INFO:Initializing create_model()
2023-12-19 17:02:25,424:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7f156a265710>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7f156a1b1890>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-19 17:02:25,425:INFO:Checking exceptions
2023-12-19 17:02:25,426:INFO:Importing libraries
2023-12-19 17:02:25,426:INFO:Copying training dataset
2023-12-19 17:02:25,471:INFO:Defining folds
2023-12-19 17:02:25,471:INFO:Declaring metric variables
2023-12-19 17:02:25,498:INFO:Importing untrained model
2023-12-19 17:02:25,532:INFO:Gradient Boosting Classifier Imported successfully
2023-12-19 17:02:25,581:INFO:Starting cross validation
2023-12-19 17:02:25,597:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-20 09:16:18,347:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-20 09:16:18,348:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-20 09:16:18,349:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-20 09:16:18,349:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-12-20 09:16:25,215:INFO:PyCaret ClassificationExperiment
2023-12-20 09:16:25,215:INFO:Logging name: clf-default-name
2023-12-20 09:16:25,218:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-12-20 09:16:25,219:INFO:version 3.2.0
2023-12-20 09:16:25,219:INFO:Initializing setup()
2023-12-20 09:16:25,219:INFO:self.USI: f7db
2023-12-20 09:16:25,219:INFO:self._variable_keys: {'seed', 'n_jobs_param', 'X_train', 'target_param', 'X_test', '_ml_usecase', '_available_plots', 'exp_id', 'gpu_param', 'exp_name_log', 'fold_generator', 'gpu_n_jobs_param', 'X', 'idx', 'logging_param', 'y_test', 'pipeline', 'y', 'fold_groups_param', 'log_plots_param', 'is_multiclass', 'data', 'html_param', 'fold_shuffle_param', 'fix_imbalance', 'memory', 'y_train', 'USI'}
2023-12-20 09:16:25,219:INFO:Checking environment
2023-12-20 09:16:25,220:INFO:python_version: 3.11.6
2023-12-20 09:16:25,220:INFO:python_build: ('main', 'Oct  3 2023 00:00:00')
2023-12-20 09:16:25,232:INFO:machine: x86_64
2023-12-20 09:16:25,232:INFO:platform: Linux-6.6.6-100.fc38.x86_64-x86_64-with-glibc2.37
2023-12-20 09:16:25,233:INFO:Memory: svmem(total=16658345984, available=10278510592, percent=38.3, used=5391310848, free=5050626048, active=7376101376, inactive=3021574144, buffers=4657152, cached=6211751936, shared=649764864, slab=399978496)
2023-12-20 09:16:25,259:INFO:Physical Core: 2
2023-12-20 09:16:25,259:INFO:Logical Core: 4
2023-12-20 09:16:25,259:INFO:Checking libraries
2023-12-20 09:16:25,260:INFO:System:
2023-12-20 09:16:25,260:INFO:    python: 3.11.6 (main, Oct  3 2023, 00:00:00) [GCC 13.2.1 20230728 (Red Hat 13.2.1-1)]
2023-12-20 09:16:25,260:INFO:executable: /home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/bin/python
2023-12-20 09:16:25,262:INFO:   machine: Linux-6.6.6-100.fc38.x86_64-x86_64-with-glibc2.37
2023-12-20 09:16:25,266:INFO:PyCaret required dependencies:
2023-12-20 09:16:25,521:INFO:                 pip: 23.3.2
2023-12-20 09:16:25,521:INFO:          setuptools: 65.5.1
2023-12-20 09:16:25,521:INFO:             pycaret: 3.2.0
2023-12-20 09:16:25,522:INFO:             IPython: 8.18.1
2023-12-20 09:16:25,522:INFO:          ipywidgets: 8.1.1
2023-12-20 09:16:25,522:INFO:                tqdm: 4.66.1
2023-12-20 09:16:25,522:INFO:               numpy: 1.25.2
2023-12-20 09:16:25,522:INFO:              pandas: 1.5.3
2023-12-20 09:16:25,522:INFO:              jinja2: 3.1.2
2023-12-20 09:16:25,523:INFO:               scipy: 1.10.1
2023-12-20 09:16:25,523:INFO:              joblib: 1.3.2
2023-12-20 09:16:25,523:INFO:             sklearn: 1.2.2
2023-12-20 09:16:25,523:INFO:                pyod: 1.1.2
2023-12-20 09:16:25,524:INFO:            imblearn: 0.11.0
2023-12-20 09:16:25,524:INFO:   category_encoders: 2.6.3
2023-12-20 09:16:25,524:INFO:            lightgbm: 4.1.0
2023-12-20 09:16:25,524:INFO:               numba: 0.58.1
2023-12-20 09:16:25,525:INFO:            requests: 2.31.0
2023-12-20 09:16:25,525:INFO:          matplotlib: 3.6.0
2023-12-20 09:16:25,525:INFO:          scikitplot: 0.3.7
2023-12-20 09:16:25,525:INFO:         yellowbrick: 1.5
2023-12-20 09:16:25,525:INFO:              plotly: 5.18.0
2023-12-20 09:16:25,526:INFO:    plotly-resampler: Not installed
2023-12-20 09:16:25,526:INFO:             kaleido: 0.2.1
2023-12-20 09:16:25,526:INFO:           schemdraw: 0.15
2023-12-20 09:16:25,527:INFO:         statsmodels: 0.14.1
2023-12-20 09:16:25,527:INFO:              sktime: 0.21.1
2023-12-20 09:16:25,527:INFO:               tbats: 1.1.3
2023-12-20 09:16:25,527:INFO:            pmdarima: 2.0.4
2023-12-20 09:16:25,527:INFO:              psutil: 5.9.7
2023-12-20 09:16:25,528:INFO:          markupsafe: 2.1.3
2023-12-20 09:16:25,528:INFO:             pickle5: Not installed
2023-12-20 09:16:25,528:INFO:         cloudpickle: 3.0.0
2023-12-20 09:16:25,528:INFO:         deprecation: 2.1.0
2023-12-20 09:16:25,528:INFO:              xxhash: 3.4.1
2023-12-20 09:16:25,529:INFO:           wurlitzer: 3.0.3
2023-12-20 09:16:25,529:INFO:PyCaret optional dependencies:
2023-12-20 09:16:25,869:INFO:                shap: Not installed
2023-12-20 09:16:25,870:INFO:           interpret: Not installed
2023-12-20 09:16:25,871:INFO:                umap: Not installed
2023-12-20 09:16:25,871:INFO:     ydata_profiling: Not installed
2023-12-20 09:16:25,873:INFO:  explainerdashboard: Not installed
2023-12-20 09:16:25,873:INFO:             autoviz: Not installed
2023-12-20 09:16:25,874:INFO:           fairlearn: Not installed
2023-12-20 09:16:25,874:INFO:          deepchecks: Not installed
2023-12-20 09:16:25,874:INFO:             xgboost: Not installed
2023-12-20 09:16:25,874:INFO:            catboost: Not installed
2023-12-20 09:16:25,874:INFO:              kmodes: Not installed
2023-12-20 09:16:25,875:INFO:             mlxtend: Not installed
2023-12-20 09:16:25,875:INFO:       statsforecast: Not installed
2023-12-20 09:16:25,875:INFO:        tune_sklearn: Not installed
2023-12-20 09:16:25,875:INFO:                 ray: Not installed
2023-12-20 09:16:25,875:INFO:            hyperopt: Not installed
2023-12-20 09:16:25,876:INFO:              optuna: Not installed
2023-12-20 09:16:25,876:INFO:               skopt: Not installed
2023-12-20 09:16:25,876:INFO:              mlflow: Not installed
2023-12-20 09:16:25,876:INFO:              gradio: Not installed
2023-12-20 09:16:25,877:INFO:             fastapi: Not installed
2023-12-20 09:16:25,877:INFO:             uvicorn: Not installed
2023-12-20 09:16:25,877:INFO:              m2cgen: Not installed
2023-12-20 09:16:25,877:INFO:           evidently: Not installed
2023-12-20 09:16:25,878:INFO:               fugue: Not installed
2023-12-20 09:16:25,878:INFO:           streamlit: Not installed
2023-12-20 09:16:25,879:INFO:             prophet: Not installed
2023-12-20 09:16:25,880:INFO:None
2023-12-20 09:16:25,880:INFO:Set up data.
2023-12-20 09:16:27,378:INFO:Set up folding strategy.
2023-12-20 09:16:27,379:INFO:Set up train/test split.
2023-12-20 09:16:27,484:INFO:Set up index.
2023-12-20 09:16:27,484:INFO:Assigning column types.
2023-12-20 09:16:27,579:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-12-20 09:16:27,967:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-12-20 09:16:27,991:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-20 09:16:28,286:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-20 09:16:28,287:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-20 09:16:28,724:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-12-20 09:16:28,730:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-20 09:16:29,002:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-20 09:16:29,004:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-20 09:16:29,005:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-12-20 09:16:29,401:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-20 09:16:29,749:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-20 09:16:29,751:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-20 09:16:30,209:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-12-20 09:16:30,487:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-20 09:16:30,489:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-20 09:16:30,491:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-12-20 09:16:31,394:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-20 09:16:31,396:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-20 09:16:32,147:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-20 09:16:32,149:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-20 09:16:32,156:INFO:Preparing preprocessing pipeline...
2023-12-20 09:16:32,165:INFO:Set up simple imputation.
2023-12-20 09:16:32,445:INFO:Finished creating preprocessing pipeline.
2023-12-20 09:16:32,498:INFO:Pipeline: Pipeline(memory=FastMemory(location=/tmp/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['0', '1', '2', '3', '4', '5', '6',
                                             '7', '8', '9', '10', '11', '12',
                                             '13', '14', '15', '16', '17', '18',
                                             '19', '20', '21', '22', '23', '24',
                                             '25', '26', '27', '28', '29', ...],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecated'))),
                ('categorical_imputer',
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated')))],
         verbose=False)
2023-12-20 09:16:32,498:INFO:Creating final display dataframe.
2023-12-20 09:16:34,216:INFO:Setup _display_container:                     Description             Value
0                    Session id               605
1                        Target            target
2                   Target type            Binary
3           Original data shape       (1093, 513)
4        Transformed data shape       (1093, 513)
5   Transformed train set shape        (765, 513)
6    Transformed test set shape        (328, 513)
7              Numeric features               512
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              f7db
2023-12-20 09:16:35,183:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-20 09:16:35,185:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-20 09:16:35,814:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-20 09:16:35,815:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-12-20 09:16:35,820:INFO:setup() successfully completed in 10.63s...............
2023-12-20 09:16:35,821:INFO:Initializing compare_models()
2023-12-20 09:16:35,821:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, include=None, exclude=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>})
2023-12-20 09:16:35,821:INFO:Checking exceptions
2023-12-20 09:16:35,852:INFO:Preparing display monitor
2023-12-20 09:16:36,197:INFO:Initializing Logistic Regression
2023-12-20 09:16:36,197:INFO:Total runtime is 8.58306884765625e-06 minutes
2023-12-20 09:16:36,233:INFO:SubProcess create_model() called ==================================
2023-12-20 09:16:36,234:INFO:Initializing create_model()
2023-12-20 09:16:36,234:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fe6623bbb50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-20 09:16:36,235:INFO:Checking exceptions
2023-12-20 09:16:36,237:INFO:Importing libraries
2023-12-20 09:16:36,237:INFO:Copying training dataset
2023-12-20 09:16:36,289:INFO:Defining folds
2023-12-20 09:16:36,289:INFO:Declaring metric variables
2023-12-20 09:16:36,362:INFO:Importing untrained model
2023-12-20 09:16:36,437:INFO:Logistic Regression Imported successfully
2023-12-20 09:16:36,577:INFO:Starting cross validation
2023-12-20 09:16:36,604:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-20 09:17:00,750:INFO:Calculating mean and std
2023-12-20 09:17:00,771:INFO:Creating metrics dataframe
2023-12-20 09:17:00,830:INFO:Uploading results into container
2023-12-20 09:17:00,833:INFO:Uploading model into container now
2023-12-20 09:17:00,836:INFO:_master_model_container: 1
2023-12-20 09:17:00,837:INFO:_display_container: 2
2023-12-20 09:17:00,839:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=605, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-12-20 09:17:00,839:INFO:create_model() successfully completed......................................
2023-12-20 09:17:01,190:INFO:SubProcess create_model() end ==================================
2023-12-20 09:17:01,190:INFO:Creating metrics dataframe
2023-12-20 09:17:01,246:INFO:Initializing K Neighbors Classifier
2023-12-20 09:17:01,246:INFO:Total runtime is 0.4174886067708333 minutes
2023-12-20 09:17:01,277:INFO:SubProcess create_model() called ==================================
2023-12-20 09:17:01,278:INFO:Initializing create_model()
2023-12-20 09:17:01,280:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fe6623bbb50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-20 09:17:01,280:INFO:Checking exceptions
2023-12-20 09:17:01,280:INFO:Importing libraries
2023-12-20 09:17:01,281:INFO:Copying training dataset
2023-12-20 09:17:01,339:INFO:Defining folds
2023-12-20 09:17:01,340:INFO:Declaring metric variables
2023-12-20 09:17:01,359:INFO:Importing untrained model
2023-12-20 09:17:01,380:INFO:K Neighbors Classifier Imported successfully
2023-12-20 09:17:01,420:INFO:Starting cross validation
2023-12-20 09:17:01,435:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-20 09:17:03,948:INFO:Calculating mean and std
2023-12-20 09:17:03,963:INFO:Creating metrics dataframe
2023-12-20 09:17:04,011:INFO:Uploading results into container
2023-12-20 09:17:04,013:INFO:Uploading model into container now
2023-12-20 09:17:04,015:INFO:_master_model_container: 2
2023-12-20 09:17:04,016:INFO:_display_container: 2
2023-12-20 09:17:04,017:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-12-20 09:17:04,018:INFO:create_model() successfully completed......................................
2023-12-20 09:17:04,275:INFO:SubProcess create_model() end ==================================
2023-12-20 09:17:04,276:INFO:Creating metrics dataframe
2023-12-20 09:17:04,337:INFO:Initializing Naive Bayes
2023-12-20 09:17:04,338:INFO:Total runtime is 0.46901673475901284 minutes
2023-12-20 09:17:04,358:INFO:SubProcess create_model() called ==================================
2023-12-20 09:17:04,359:INFO:Initializing create_model()
2023-12-20 09:17:04,360:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fe6623bbb50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-20 09:17:04,360:INFO:Checking exceptions
2023-12-20 09:17:04,360:INFO:Importing libraries
2023-12-20 09:17:04,362:INFO:Copying training dataset
2023-12-20 09:17:04,409:INFO:Defining folds
2023-12-20 09:17:04,409:INFO:Declaring metric variables
2023-12-20 09:17:04,428:INFO:Importing untrained model
2023-12-20 09:17:04,448:INFO:Naive Bayes Imported successfully
2023-12-20 09:17:04,489:INFO:Starting cross validation
2023-12-20 09:17:04,501:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-20 09:17:06,320:INFO:Calculating mean and std
2023-12-20 09:17:06,332:INFO:Creating metrics dataframe
2023-12-20 09:17:06,373:INFO:Uploading results into container
2023-12-20 09:17:06,376:INFO:Uploading model into container now
2023-12-20 09:17:06,378:INFO:_master_model_container: 3
2023-12-20 09:17:06,379:INFO:_display_container: 2
2023-12-20 09:17:06,380:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-12-20 09:17:06,380:INFO:create_model() successfully completed......................................
2023-12-20 09:17:06,592:INFO:SubProcess create_model() end ==================================
2023-12-20 09:17:06,592:INFO:Creating metrics dataframe
2023-12-20 09:17:06,647:INFO:Initializing Decision Tree Classifier
2023-12-20 09:17:06,647:INFO:Total runtime is 0.5075092673301697 minutes
2023-12-20 09:17:06,673:INFO:SubProcess create_model() called ==================================
2023-12-20 09:17:06,674:INFO:Initializing create_model()
2023-12-20 09:17:06,675:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fe6623bbb50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-20 09:17:06,676:INFO:Checking exceptions
2023-12-20 09:17:06,677:INFO:Importing libraries
2023-12-20 09:17:06,677:INFO:Copying training dataset
2023-12-20 09:17:06,727:INFO:Defining folds
2023-12-20 09:17:06,728:INFO:Declaring metric variables
2023-12-20 09:17:06,757:INFO:Importing untrained model
2023-12-20 09:17:06,785:INFO:Decision Tree Classifier Imported successfully
2023-12-20 09:17:06,854:INFO:Starting cross validation
2023-12-20 09:17:06,882:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-20 09:17:14,713:INFO:Calculating mean and std
2023-12-20 09:17:14,729:INFO:Creating metrics dataframe
2023-12-20 09:17:14,768:INFO:Uploading results into container
2023-12-20 09:17:14,771:INFO:Uploading model into container now
2023-12-20 09:17:14,773:INFO:_master_model_container: 4
2023-12-20 09:17:14,773:INFO:_display_container: 2
2023-12-20 09:17:14,775:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=605, splitter='best')
2023-12-20 09:17:14,776:INFO:create_model() successfully completed......................................
2023-12-20 09:17:15,082:INFO:SubProcess create_model() end ==================================
2023-12-20 09:17:15,082:INFO:Creating metrics dataframe
2023-12-20 09:17:15,149:INFO:Initializing SVM - Linear Kernel
2023-12-20 09:17:15,149:INFO:Total runtime is 0.6492117404937744 minutes
2023-12-20 09:17:15,168:INFO:SubProcess create_model() called ==================================
2023-12-20 09:17:15,169:INFO:Initializing create_model()
2023-12-20 09:17:15,170:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fe6623bbb50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-20 09:17:15,170:INFO:Checking exceptions
2023-12-20 09:17:15,170:INFO:Importing libraries
2023-12-20 09:17:15,170:INFO:Copying training dataset
2023-12-20 09:17:15,218:INFO:Defining folds
2023-12-20 09:17:15,219:INFO:Declaring metric variables
2023-12-20 09:17:15,251:INFO:Importing untrained model
2023-12-20 09:17:15,281:INFO:SVM - Linear Kernel Imported successfully
2023-12-20 09:17:15,326:INFO:Starting cross validation
2023-12-20 09:17:15,340:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-20 09:17:15,813:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-20 09:17:16,096:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-20 09:17:16,116:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-20 09:17:16,402:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-20 09:17:16,508:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-20 09:17:16,923:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-20 09:17:17,236:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-20 09:17:17,283:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-20 09:17:17,294:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-20 09:17:17,563:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-12-20 09:17:17,728:INFO:Calculating mean and std
2023-12-20 09:17:17,734:INFO:Creating metrics dataframe
2023-12-20 09:17:17,754:INFO:Uploading results into container
2023-12-20 09:17:17,758:INFO:Uploading model into container now
2023-12-20 09:17:17,760:INFO:_master_model_container: 5
2023-12-20 09:17:17,760:INFO:_display_container: 2
2023-12-20 09:17:17,763:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=605, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-12-20 09:17:17,763:INFO:create_model() successfully completed......................................
2023-12-20 09:17:17,996:INFO:SubProcess create_model() end ==================================
2023-12-20 09:17:17,997:INFO:Creating metrics dataframe
2023-12-20 09:17:18,066:INFO:Initializing Ridge Classifier
2023-12-20 09:17:18,067:INFO:Total runtime is 0.6978424429893494 minutes
2023-12-20 09:17:18,094:INFO:SubProcess create_model() called ==================================
2023-12-20 09:17:18,095:INFO:Initializing create_model()
2023-12-20 09:17:18,095:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fe6623bbb50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-20 09:17:18,098:INFO:Checking exceptions
2023-12-20 09:17:18,099:INFO:Importing libraries
2023-12-20 09:17:18,099:INFO:Copying training dataset
2023-12-20 09:17:18,161:INFO:Defining folds
2023-12-20 09:17:18,162:INFO:Declaring metric variables
2023-12-20 09:17:18,181:INFO:Importing untrained model
2023-12-20 09:17:18,202:INFO:Ridge Classifier Imported successfully
2023-12-20 09:17:18,260:INFO:Starting cross validation
2023-12-20 09:17:18,274:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-20 09:17:18,858:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-20 09:17:18,895:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-20 09:17:18,914:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-20 09:17:19,146:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-20 09:17:19,240:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-20 09:17:19,509:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-20 09:17:19,609:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-20 09:17:19,940:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-20 09:17:19,948:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-20 09:17:19,997:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
           ~~~~~^^^^^^^^
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-12-20 09:17:20,103:INFO:Calculating mean and std
2023-12-20 09:17:20,115:INFO:Creating metrics dataframe
2023-12-20 09:17:20,145:INFO:Uploading results into container
2023-12-20 09:17:20,149:INFO:Uploading model into container now
2023-12-20 09:17:20,152:INFO:_master_model_container: 6
2023-12-20 09:17:20,152:INFO:_display_container: 2
2023-12-20 09:17:20,154:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=605, solver='auto',
                tol=0.0001)
2023-12-20 09:17:20,154:INFO:create_model() successfully completed......................................
2023-12-20 09:17:20,498:INFO:SubProcess create_model() end ==================================
2023-12-20 09:17:20,498:INFO:Creating metrics dataframe
2023-12-20 09:17:20,577:INFO:Initializing Random Forest Classifier
2023-12-20 09:17:20,578:INFO:Total runtime is 0.7396833777427674 minutes
2023-12-20 09:17:20,595:INFO:SubProcess create_model() called ==================================
2023-12-20 09:17:20,596:INFO:Initializing create_model()
2023-12-20 09:17:20,596:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fe6623bbb50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-20 09:17:20,597:INFO:Checking exceptions
2023-12-20 09:17:20,597:INFO:Importing libraries
2023-12-20 09:17:20,598:INFO:Copying training dataset
2023-12-20 09:17:20,651:INFO:Defining folds
2023-12-20 09:17:20,651:INFO:Declaring metric variables
2023-12-20 09:17:20,674:INFO:Importing untrained model
2023-12-20 09:17:20,698:INFO:Random Forest Classifier Imported successfully
2023-12-20 09:17:20,740:INFO:Starting cross validation
2023-12-20 09:17:20,754:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-20 09:17:40,181:INFO:Calculating mean and std
2023-12-20 09:17:40,186:INFO:Creating metrics dataframe
2023-12-20 09:17:40,201:INFO:Uploading results into container
2023-12-20 09:17:40,206:INFO:Uploading model into container now
2023-12-20 09:17:40,209:INFO:_master_model_container: 7
2023-12-20 09:17:40,209:INFO:_display_container: 2
2023-12-20 09:17:40,212:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=605, verbose=0, warm_start=False)
2023-12-20 09:17:40,212:INFO:create_model() successfully completed......................................
2023-12-20 09:17:40,435:INFO:SubProcess create_model() end ==================================
2023-12-20 09:17:40,436:INFO:Creating metrics dataframe
2023-12-20 09:17:40,526:INFO:Initializing Quadratic Discriminant Analysis
2023-12-20 09:17:40,527:INFO:Total runtime is 1.0721756219863892 minutes
2023-12-20 09:17:40,547:INFO:SubProcess create_model() called ==================================
2023-12-20 09:17:40,549:INFO:Initializing create_model()
2023-12-20 09:17:40,550:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fe6623bbb50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-20 09:17:40,550:INFO:Checking exceptions
2023-12-20 09:17:40,551:INFO:Importing libraries
2023-12-20 09:17:40,551:INFO:Copying training dataset
2023-12-20 09:17:40,593:INFO:Defining folds
2023-12-20 09:17:40,597:INFO:Declaring metric variables
2023-12-20 09:17:40,628:INFO:Importing untrained model
2023-12-20 09:17:40,650:INFO:Quadratic Discriminant Analysis Imported successfully
2023-12-20 09:17:40,682:INFO:Starting cross validation
2023-12-20 09:17:40,698:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-20 09:17:41,374:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-20 09:17:41,439:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-20 09:17:41,642:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-20 09:17:41,887:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-20 09:17:42,591:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-20 09:17:42,967:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-20 09:17:42,991:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-20 09:17:43,631:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-20 09:17:44,036:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-20 09:17:44,150:WARNING:/home/zaphyra/Documents/Vscode/iadev-py/numpy_py/door/.venvdoor/lib64/python3.11/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-12-20 09:17:44,706:INFO:Calculating mean and std
2023-12-20 09:17:44,710:INFO:Creating metrics dataframe
2023-12-20 09:17:44,727:INFO:Uploading results into container
2023-12-20 09:17:44,730:INFO:Uploading model into container now
2023-12-20 09:17:44,731:INFO:_master_model_container: 8
2023-12-20 09:17:44,731:INFO:_display_container: 2
2023-12-20 09:17:44,732:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-12-20 09:17:44,732:INFO:create_model() successfully completed......................................
2023-12-20 09:17:44,961:INFO:SubProcess create_model() end ==================================
2023-12-20 09:17:44,964:INFO:Creating metrics dataframe
2023-12-20 09:17:45,040:INFO:Initializing Ada Boost Classifier
2023-12-20 09:17:45,041:INFO:Total runtime is 1.1474046945571899 minutes
2023-12-20 09:17:45,060:INFO:SubProcess create_model() called ==================================
2023-12-20 09:17:45,062:INFO:Initializing create_model()
2023-12-20 09:17:45,062:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fe6623bbb50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-20 09:17:45,062:INFO:Checking exceptions
2023-12-20 09:17:45,063:INFO:Importing libraries
2023-12-20 09:17:45,063:INFO:Copying training dataset
2023-12-20 09:17:45,100:INFO:Defining folds
2023-12-20 09:17:45,101:INFO:Declaring metric variables
2023-12-20 09:17:45,123:INFO:Importing untrained model
2023-12-20 09:17:45,153:INFO:Ada Boost Classifier Imported successfully
2023-12-20 09:17:45,219:INFO:Starting cross validation
2023-12-20 09:17:45,237:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-20 09:18:30,039:INFO:Calculating mean and std
2023-12-20 09:18:30,044:INFO:Creating metrics dataframe
2023-12-20 09:18:30,067:INFO:Uploading results into container
2023-12-20 09:18:30,073:INFO:Uploading model into container now
2023-12-20 09:18:30,076:INFO:_master_model_container: 9
2023-12-20 09:18:30,077:INFO:_display_container: 2
2023-12-20 09:18:30,079:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=605)
2023-12-20 09:18:30,079:INFO:create_model() successfully completed......................................
2023-12-20 09:18:30,414:INFO:SubProcess create_model() end ==================================
2023-12-20 09:18:30,415:INFO:Creating metrics dataframe
2023-12-20 09:18:30,500:INFO:Initializing Gradient Boosting Classifier
2023-12-20 09:18:30,503:INFO:Total runtime is 1.9050977905591329 minutes
2023-12-20 09:18:30,526:INFO:SubProcess create_model() called ==================================
2023-12-20 09:18:30,527:INFO:Initializing create_model()
2023-12-20 09:18:30,528:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fe6623bbb50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-20 09:18:30,531:INFO:Checking exceptions
2023-12-20 09:18:30,533:INFO:Importing libraries
2023-12-20 09:18:30,534:INFO:Copying training dataset
2023-12-20 09:18:30,592:INFO:Defining folds
2023-12-20 09:18:30,593:INFO:Declaring metric variables
2023-12-20 09:18:30,622:INFO:Importing untrained model
2023-12-20 09:18:30,664:INFO:Gradient Boosting Classifier Imported successfully
2023-12-20 09:18:30,714:INFO:Starting cross validation
2023-12-20 09:18:30,729:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-20 09:21:34,738:INFO:Calculating mean and std
2023-12-20 09:21:34,741:INFO:Creating metrics dataframe
2023-12-20 09:21:34,756:INFO:Uploading results into container
2023-12-20 09:21:34,758:INFO:Uploading model into container now
2023-12-20 09:21:34,760:INFO:_master_model_container: 10
2023-12-20 09:21:34,764:INFO:_display_container: 2
2023-12-20 09:21:34,767:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=605, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-12-20 09:21:34,768:INFO:create_model() successfully completed......................................
2023-12-20 09:21:34,967:INFO:SubProcess create_model() end ==================================
2023-12-20 09:21:34,968:INFO:Creating metrics dataframe
2023-12-20 09:21:35,019:INFO:Initializing Linear Discriminant Analysis
2023-12-20 09:21:35,020:INFO:Total runtime is 4.980382088820139 minutes
2023-12-20 09:21:35,037:INFO:SubProcess create_model() called ==================================
2023-12-20 09:21:35,038:INFO:Initializing create_model()
2023-12-20 09:21:35,042:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fe6623bbb50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-20 09:21:35,042:INFO:Checking exceptions
2023-12-20 09:21:35,043:INFO:Importing libraries
2023-12-20 09:21:35,043:INFO:Copying training dataset
2023-12-20 09:21:35,093:INFO:Defining folds
2023-12-20 09:21:35,093:INFO:Declaring metric variables
2023-12-20 09:21:35,115:INFO:Importing untrained model
2023-12-20 09:21:35,134:INFO:Linear Discriminant Analysis Imported successfully
2023-12-20 09:21:35,165:INFO:Starting cross validation
2023-12-20 09:21:35,174:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-20 09:21:39,784:INFO:Calculating mean and std
2023-12-20 09:21:39,788:INFO:Creating metrics dataframe
2023-12-20 09:21:39,799:INFO:Uploading results into container
2023-12-20 09:21:39,801:INFO:Uploading model into container now
2023-12-20 09:21:39,802:INFO:_master_model_container: 11
2023-12-20 09:21:39,802:INFO:_display_container: 2
2023-12-20 09:21:39,803:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-12-20 09:21:39,804:INFO:create_model() successfully completed......................................
2023-12-20 09:21:39,966:INFO:SubProcess create_model() end ==================================
2023-12-20 09:21:39,967:INFO:Creating metrics dataframe
2023-12-20 09:21:40,024:INFO:Initializing Extra Trees Classifier
2023-12-20 09:21:40,025:INFO:Total runtime is 5.06380302508672 minutes
2023-12-20 09:21:40,042:INFO:SubProcess create_model() called ==================================
2023-12-20 09:21:40,044:INFO:Initializing create_model()
2023-12-20 09:21:40,044:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fe6623bbb50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-20 09:21:40,045:INFO:Checking exceptions
2023-12-20 09:21:40,045:INFO:Importing libraries
2023-12-20 09:21:40,045:INFO:Copying training dataset
2023-12-20 09:21:40,074:INFO:Defining folds
2023-12-20 09:21:40,075:INFO:Declaring metric variables
2023-12-20 09:21:40,094:INFO:Importing untrained model
2023-12-20 09:21:40,116:INFO:Extra Trees Classifier Imported successfully
2023-12-20 09:21:40,161:INFO:Starting cross validation
2023-12-20 09:21:40,173:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-20 09:21:45,951:INFO:Calculating mean and std
2023-12-20 09:21:45,956:INFO:Creating metrics dataframe
2023-12-20 09:21:45,967:INFO:Uploading results into container
2023-12-20 09:21:45,968:INFO:Uploading model into container now
2023-12-20 09:21:45,969:INFO:_master_model_container: 12
2023-12-20 09:21:45,970:INFO:_display_container: 2
2023-12-20 09:21:45,971:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=605, verbose=0, warm_start=False)
2023-12-20 09:21:45,971:INFO:create_model() successfully completed......................................
2023-12-20 09:21:46,152:INFO:SubProcess create_model() end ==================================
2023-12-20 09:21:46,153:INFO:Creating metrics dataframe
2023-12-20 09:21:46,217:INFO:Initializing Light Gradient Boosting Machine
2023-12-20 09:21:46,217:INFO:Total runtime is 5.167008006572723 minutes
2023-12-20 09:21:46,230:INFO:SubProcess create_model() called ==================================
2023-12-20 09:21:46,231:INFO:Initializing create_model()
2023-12-20 09:21:46,232:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fe6623bbb50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-20 09:21:46,233:INFO:Checking exceptions
2023-12-20 09:21:46,233:INFO:Importing libraries
2023-12-20 09:21:46,233:INFO:Copying training dataset
2023-12-20 09:21:46,264:INFO:Defining folds
2023-12-20 09:21:46,264:INFO:Declaring metric variables
2023-12-20 09:21:46,277:INFO:Importing untrained model
2023-12-20 09:21:46,302:INFO:Light Gradient Boosting Machine Imported successfully
2023-12-20 09:21:46,332:INFO:Starting cross validation
2023-12-20 09:21:46,345:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-20 09:39:27,389:INFO:Calculating mean and std
2023-12-20 09:39:27,399:INFO:Creating metrics dataframe
2023-12-20 09:39:27,412:INFO:Uploading results into container
2023-12-20 09:39:27,414:INFO:Uploading model into container now
2023-12-20 09:39:27,415:INFO:_master_model_container: 13
2023-12-20 09:39:27,415:INFO:_display_container: 2
2023-12-20 09:39:27,417:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=605, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2023-12-20 09:39:27,417:INFO:create_model() successfully completed......................................
2023-12-20 09:39:27,579:INFO:SubProcess create_model() end ==================================
2023-12-20 09:39:27,580:INFO:Creating metrics dataframe
2023-12-20 09:39:27,641:INFO:Initializing Dummy Classifier
2023-12-20 09:39:27,641:INFO:Total runtime is 22.857412676016487 minutes
2023-12-20 09:39:27,657:INFO:SubProcess create_model() called ==================================
2023-12-20 09:39:27,658:INFO:Initializing create_model()
2023-12-20 09:39:27,658:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fe6623bbb50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-20 09:39:27,658:INFO:Checking exceptions
2023-12-20 09:39:27,658:INFO:Importing libraries
2023-12-20 09:39:27,659:INFO:Copying training dataset
2023-12-20 09:39:27,690:INFO:Defining folds
2023-12-20 09:39:27,691:INFO:Declaring metric variables
2023-12-20 09:39:27,706:INFO:Importing untrained model
2023-12-20 09:39:27,723:INFO:Dummy Classifier Imported successfully
2023-12-20 09:39:27,751:INFO:Starting cross validation
2023-12-20 09:39:27,757:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-20 09:39:28,434:INFO:Calculating mean and std
2023-12-20 09:39:28,438:INFO:Creating metrics dataframe
2023-12-20 09:39:28,449:INFO:Uploading results into container
2023-12-20 09:39:28,451:INFO:Uploading model into container now
2023-12-20 09:39:28,453:INFO:_master_model_container: 14
2023-12-20 09:39:28,453:INFO:_display_container: 2
2023-12-20 09:39:28,454:INFO:DummyClassifier(constant=None, random_state=605, strategy='prior')
2023-12-20 09:39:28,454:INFO:create_model() successfully completed......................................
2023-12-20 09:39:28,626:INFO:SubProcess create_model() end ==================================
2023-12-20 09:39:28,627:INFO:Creating metrics dataframe
2023-12-20 09:39:28,732:INFO:Initializing create_model()
2023-12-20 09:39:28,733:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=605, verbose=0, warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-20 09:39:28,733:INFO:Checking exceptions
2023-12-20 09:39:28,742:INFO:Importing libraries
2023-12-20 09:39:28,743:INFO:Copying training dataset
2023-12-20 09:39:28,770:INFO:Defining folds
2023-12-20 09:39:28,770:INFO:Declaring metric variables
2023-12-20 09:39:28,771:INFO:Importing untrained model
2023-12-20 09:39:28,771:INFO:Declaring custom model
2023-12-20 09:39:28,773:INFO:Extra Trees Classifier Imported successfully
2023-12-20 09:39:28,779:INFO:Cross validation set to False
2023-12-20 09:39:28,779:INFO:Fitting Model
2023-12-20 09:39:29,518:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=605, verbose=0, warm_start=False)
2023-12-20 09:39:29,518:INFO:create_model() successfully completed......................................
2023-12-20 09:39:29,888:INFO:_master_model_container: 14
2023-12-20 09:39:29,890:INFO:_display_container: 2
2023-12-20 09:39:29,893:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=605, verbose=0, warm_start=False)
2023-12-20 09:39:29,895:INFO:compare_models() successfully completed......................................
2023-12-20 09:39:29,899:INFO:Initializing automl()
2023-12-20 09:39:29,900:INFO:automl(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, optimize=Accuracy, use_holdout=False, turbo=True, return_train_score=False)
2023-12-20 09:39:29,901:INFO:Model Selection Basis : CV Results on Training set
2023-12-20 09:39:29,901:INFO:Checking model 0
2023-12-20 09:39:29,902:INFO:Checking model 1
2023-12-20 09:39:29,903:INFO:Checking model 2
2023-12-20 09:39:29,905:INFO:Checking model 3
2023-12-20 09:39:29,906:INFO:Checking model 4
2023-12-20 09:39:29,907:INFO:Checking model 5
2023-12-20 09:39:29,908:INFO:Checking model 6
2023-12-20 09:39:29,909:INFO:Checking model 7
2023-12-20 09:39:29,911:INFO:Checking model 8
2023-12-20 09:39:29,912:INFO:Checking model 9
2023-12-20 09:39:29,913:INFO:Checking model 10
2023-12-20 09:39:29,914:INFO:Checking model 11
2023-12-20 09:39:29,915:INFO:Checking model 12
2023-12-20 09:39:29,916:INFO:Checking model 13
2023-12-20 09:39:29,919:INFO:Initializing create_model()
2023-12-20 09:39:29,919:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=605, verbose=0, warm_start=False), fold=None, round=4, cross_validation=False, predict=False, fit_kwargs=None, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-20 09:39:29,919:INFO:Checking exceptions
2023-12-20 09:39:29,925:INFO:Importing libraries
2023-12-20 09:39:29,926:INFO:Copying training dataset
2023-12-20 09:39:29,954:INFO:Defining folds
2023-12-20 09:39:29,954:INFO:Declaring metric variables
2023-12-20 09:39:29,955:INFO:Importing untrained model
2023-12-20 09:39:29,955:INFO:Declaring custom model
2023-12-20 09:39:29,957:INFO:Extra Trees Classifier Imported successfully
2023-12-20 09:39:29,964:INFO:Cross validation set to False
2023-12-20 09:39:29,965:INFO:Fitting Model
2023-12-20 09:39:30,686:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=605, verbose=0, warm_start=False)
2023-12-20 09:39:30,686:INFO:create_model() successfully completed......................................
2023-12-20 09:39:31,015:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=605, verbose=0, warm_start=False)
2023-12-20 09:39:31,016:INFO:automl() successfully completed......................................
2023-12-20 09:39:31,018:INFO:Initializing tune_model()
2023-12-20 09:39:31,019:INFO:tune_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=605, verbose=0, warm_start=False), fold=None, round=4, n_iter=10, custom_grid=None, optimize=Accuracy, custom_scorer=None, search_library=scikit-learn, search_algorithm=None, early_stopping=False, early_stopping_max_iters=10, choose_better=True, fit_kwargs=None, groups=None, return_tuner=False, verbose=True, tuner_verbose=True, return_train_score=False, kwargs={})
2023-12-20 09:39:31,019:INFO:Checking exceptions
2023-12-20 09:39:31,078:INFO:Copying training dataset
2023-12-20 09:39:31,105:INFO:Checking base model
2023-12-20 09:39:31,105:INFO:Base model : Extra Trees Classifier
2023-12-20 09:39:31,128:INFO:Declaring metric variables
2023-12-20 09:39:31,149:INFO:Defining Hyperparameters
2023-12-20 09:39:31,471:INFO:Tuning with n_jobs=-1
2023-12-20 09:39:31,471:INFO:Initializing RandomizedSearchCV
2023-12-20 09:41:37,719:INFO:best_params: {'actual_estimator__n_estimators': 190, 'actual_estimator__min_samples_split': 9, 'actual_estimator__min_samples_leaf': 2, 'actual_estimator__min_impurity_decrease': 0.0005, 'actual_estimator__max_features': 'sqrt', 'actual_estimator__max_depth': 10, 'actual_estimator__criterion': 'entropy', 'actual_estimator__class_weight': {}, 'actual_estimator__bootstrap': False}
2023-12-20 09:41:37,722:INFO:Hyperparameter search completed
2023-12-20 09:41:37,722:INFO:SubProcess create_model() called ==================================
2023-12-20 09:41:37,724:INFO:Initializing create_model()
2023-12-20 09:41:37,725:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=605, verbose=0, warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=True, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fe66a25fbd0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={'n_estimators': 190, 'min_samples_split': 9, 'min_samples_leaf': 2, 'min_impurity_decrease': 0.0005, 'max_features': 'sqrt', 'max_depth': 10, 'criterion': 'entropy', 'class_weight': {}, 'bootstrap': False})
2023-12-20 09:41:37,725:INFO:Checking exceptions
2023-12-20 09:41:37,727:INFO:Importing libraries
2023-12-20 09:41:37,727:INFO:Copying training dataset
2023-12-20 09:41:37,754:INFO:Defining folds
2023-12-20 09:41:37,754:INFO:Declaring metric variables
2023-12-20 09:41:37,766:INFO:Importing untrained model
2023-12-20 09:41:37,767:INFO:Declaring custom model
2023-12-20 09:41:37,783:INFO:Extra Trees Classifier Imported successfully
2023-12-20 09:41:37,812:INFO:Starting cross validation
2023-12-20 09:41:37,821:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-20 09:41:47,220:INFO:Calculating mean and std
2023-12-20 09:41:47,224:INFO:Creating metrics dataframe
2023-12-20 09:41:47,246:INFO:Finalizing model
2023-12-20 09:41:48,878:INFO:Uploading results into container
2023-12-20 09:41:48,884:INFO:Uploading model into container now
2023-12-20 09:41:48,886:INFO:_master_model_container: 15
2023-12-20 09:41:48,887:INFO:_display_container: 3
2023-12-20 09:41:48,890:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight={},
                     criterion='entropy', max_depth=10, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0005, min_samples_leaf=2,
                     min_samples_split=9, min_weight_fraction_leaf=0.0,
                     n_estimators=190, n_jobs=-1, oob_score=False,
                     random_state=605, verbose=0, warm_start=False)
2023-12-20 09:41:48,891:INFO:create_model() successfully completed......................................
2023-12-20 09:41:49,086:INFO:SubProcess create_model() end ==================================
2023-12-20 09:41:49,086:INFO:choose_better activated
2023-12-20 09:41:49,102:INFO:SubProcess create_model() called ==================================
2023-12-20 09:41:49,104:INFO:Initializing create_model()
2023-12-20 09:41:49,104:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=605, verbose=0, warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2023-12-20 09:41:49,104:INFO:Checking exceptions
2023-12-20 09:41:49,109:INFO:Importing libraries
2023-12-20 09:41:49,110:INFO:Copying training dataset
2023-12-20 09:41:49,140:INFO:Defining folds
2023-12-20 09:41:49,140:INFO:Declaring metric variables
2023-12-20 09:41:49,141:INFO:Importing untrained model
2023-12-20 09:41:49,141:INFO:Declaring custom model
2023-12-20 09:41:49,144:INFO:Extra Trees Classifier Imported successfully
2023-12-20 09:41:49,145:INFO:Starting cross validation
2023-12-20 09:41:49,151:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-12-20 09:41:54,951:INFO:Calculating mean and std
2023-12-20 09:41:54,953:INFO:Creating metrics dataframe
2023-12-20 09:41:54,959:INFO:Finalizing model
2023-12-20 09:41:55,688:INFO:Uploading results into container
2023-12-20 09:41:55,689:INFO:Uploading model into container now
2023-12-20 09:41:55,691:INFO:_master_model_container: 16
2023-12-20 09:41:55,691:INFO:_display_container: 4
2023-12-20 09:41:55,692:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=605, verbose=0, warm_start=False)
2023-12-20 09:41:55,692:INFO:create_model() successfully completed......................................
2023-12-20 09:41:55,858:INFO:SubProcess create_model() end ==================================
2023-12-20 09:41:55,861:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=605, verbose=0, warm_start=False) result for Accuracy is 0.983
2023-12-20 09:41:55,864:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight={},
                     criterion='entropy', max_depth=10, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0005, min_samples_leaf=2,
                     min_samples_split=9, min_weight_fraction_leaf=0.0,
                     n_estimators=190, n_jobs=-1, oob_score=False,
                     random_state=605, verbose=0, warm_start=False) result for Accuracy is 0.9817
2023-12-20 09:41:55,865:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=605, verbose=0, warm_start=False) is best model
2023-12-20 09:41:55,866:INFO:choose_better completed
2023-12-20 09:41:55,866:INFO:Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).
2023-12-20 09:41:55,913:INFO:_master_model_container: 16
2023-12-20 09:41:55,914:INFO:_display_container: 3
2023-12-20 09:41:55,916:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=605, verbose=0, warm_start=False)
2023-12-20 09:41:55,917:INFO:tune_model() successfully completed......................................
2023-12-20 09:41:56,099:INFO:Initializing predict_model()
2023-12-20 09:41:56,100:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fe663851a10>, estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=605, verbose=0, warm_start=False), probability_threshold=None, encoded_labels=False, raw_score=False, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x7fe6623d00e0>)
2023-12-20 09:41:56,100:INFO:Checking exceptions
2023-12-20 09:41:56,100:INFO:Preloading libraries
2023-12-20 09:41:56,107:INFO:Set up data.
2023-12-20 09:41:56,507:INFO:Set up index.
